apiVersion: v1
kind: Service
metadata:
  name: {{ include "overlock-node.fullname" . }}
  labels:
    {{- include "overlock-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $name, $port := .Values.service.ports }}
    - port: {{ $port }}
      targetPort:   
      protocol: TCP
      name: {{ $name }}
  {{- end }}
  selector:
    {{- include "overlock-node.selectorLabels" . | nindent 4 }}
