name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5

      - 
        name: Generate changelog
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: ghcr.io/overlock-network/git-chlog:0.15.4
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace;
            git config --global --add safe.directory /workspace;
            git-chglog -o .cache/changelog.md $(git describe --tags $(git rev-list --tags --max-count=1));
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --release-notes .cache/changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}